### Numpy

In [1]:
number = 13 

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [5]:
#pip install numpy to use 
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
array_a = np.array([1,2,3,4])

In [8]:
array_b = np.array([0,.5,1,1.5,2])

In [9]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [10]:
array_a[0]#erişim index ile

1

In [11]:
array_b[-1]

2.0

In [12]:
array_a[:2]

array([1, 2])

In [13]:
array_a.dtype

dtype('int32')

In [14]:
empty_array= np.array([])

In [15]:
empty_array.dtype

dtype('float64')

In [17]:
np.array([1,2,3,4], dtype=np.float_)

array([1., 2., 3., 4.])

In [18]:
array_c = np.array(["ada","lovelace"])

In [19]:
array_c.dtype

dtype('<U8')

### Dimension and shapes

In [22]:
my_array= np.array  ([
    [1,2,3],
    [4,5,6],

])

In [23]:
array_a.shape

(4,)

In [24]:
my_array.shape

(2, 3)

In [25]:
array_a.ndim


1

In [26]:
my_array.ndim#boyut

2

In [27]:
my_array.size #how many items  it has

6

In [ ]:
my_array = np.array([
    [
        [12,11,10],
        [9,7,6],
    ],
    [
        [6,5,4],
        [3,2,1],
    ]
    
    
    
])

In [29]:
my_array.ndim

3

In [ ]:
my_array.shape

(2, 2, 3)

In [31]:
my_array.size

12

### Indexing and Slicing


In [32]:
my_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
])

In [33]:
my_array[1]

array([4, 5, 6])

In [34]:
my_array[1][0]

4

In [35]:
my_array[1,2]

6

In [36]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array[:2 ,  :2]

array([[1, 2],
       [4, 5]])

In [39]:
my_array[1] = np.array([10,10,10])
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [41]:
my_array[2] = 99
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
my_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
np.arange( 0, 10.1 , 2)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [54]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
my_array = np.random.random((5,2))
my_array

array([[0.36606179, 0.41023354],
       [0.84774283, 0.9057858 ],
       [0.23572603, 0.20665702],
       [0.51623378, 0.39336242],
       [0.55791921, 0.83319655]])

In [61]:
np.random.randint(100,size=(5,5))

array([[44, 36, 51, 85, 99],
       [93, 89, 97, 33, 10],
       [42, 91, 89,  9, 60],
       [37, 55, 42, 59, 22],
       [ 1, 12, 40, 80, 27]])

In [63]:
np.linspace(1 , 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#any(), all(),full(),concatenate()

In [64]:
array1  =np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
array1 = array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.concatenate([array1,array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [69]:
array1.sum()

45

In [70]:
array1.mean()

4.5

In [71]:
array1.std()

2.8722813232690143

In [73]:
array1.var()

8.25

In [74]:
array1.sum(axis=1)

array([10, 35])

In [75]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Boolean Arrays

In [77]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [78]:
a[0], a[-1]

(0, 3)

In [79]:
a[[0,-1]]

array([0, 3])

In [80]:
a[[True,False,False,True]]

array([0, 3])

In [81]:
a >= 2

array([False, False,  True,  True])

In [82]:
a[ a>=2 ]

array([2, 3])

In [83]:
a.mean()

1.5

In [84]:
a[a > a.mean()]

array([2, 3])

In [86]:
a[~(a > a.mean())]

array([0, 1])

In [87]:
a[( a == 0) | (a == 1)]

array([0, 1])

In [88]:
a[(a <= 2 ) & (a % 2 ==0 )]

array([0, 2])

- 100 kadar rastgele tam sayılardan oluşan , 3,3 bir matris oluşturun.
- 30'dan büyük olanları boolean yöntemi ile filtreleyin 

In [94]:
my_array =np.random.randint(100,size=(3,3))
my_array

array([[51, 22, 52],
       [63, 32, 46],
       [29, 40, 88]])

In [97]:
boolean_array =my_array[my_array > 30]
boolean_array

array([51, 52, 63, 32, 46, 40, 88])

In [99]:
array2= np.array( [[1,2,3],[4,5,6]])

In [100]:
array2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
import sys

In [102]:
sys.getsizeof(10)

28

In [104]:
sys.getsizeof(1000**100)

160

In [105]:
np.dtype(int).itemsize

4

In [106]:
np.dtype(np.int8).itemsize

1

In [107]:
sys.getsizeof([1,2,3])

88

In [108]:
np.array([1,2,3]).nbytes

12

In [109]:
my_list = list(range(100000))

In [110]:
my_array = np.array(100000)

In [112]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


1410065408

In [113]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 0 ns
Wall time: 12.6 ms


333328333350000